ENG-50955: Set compatibility config to NONE for protobuf subjects (WIP)
hypertrace/schema-registry pull request #48
Opened 2024-09-30 14:20 UTC by siddhant2001

2024-09-30 14:59 UTC, ravisingal commented
@kishansairam9 is working on a  generic solution.

2024-09-30 15:15 UTC, kishansairam9 commented
> @kishansairam9 is working on a generic solution.

Adding each proto is painful, there has been a meeting where laxman and team decided on having a cron job to set for all protobufs. No need to override each proto individually. I think this is the way to go forward, my old PR is abandoned

2024-10-01 05:50 UTC, laxmanchekka requested changes

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/Dockerfile
> +RUN apt install -y curl && \
Do we need them?

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/Dockerfile
> +# create directory and copy pinot-data-metrics directory
Fix the comments

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/compatibility-changer/requirements.txt
> +certifi==2024.8.30
do we need all of them explicitly? should we omit transitive dependencies and let pip figure it out?

2024-10-01 05:50 UTC, laxmanchekka commented on helm/templates/compatibility-changer/compatibility-changer-configmap.yaml
> +      "defaultSchemaType": {{ .Values.compatibilityChanger.config.defaultSchemaType }}
schemaType -> compatibilityType

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/compatibility-changer/cron-job.py
> +host = os.getenv('SCHEMA_REGISTRY_HOST', 'localhost')
make this configurable

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/compatibility-changer/cron-job.py
> +            continue
log a warn when no version available.

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/compatibility-changer/cron-job.py
> +    logging.info(f"All subjects: {subjects}")
debug log or just log number of subjects

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/compatibility-changer/cron-job.py
> +def get_subject_version_details(subject, version):
get_subject_version_details -> get_schema_version

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/compatibility-changer/cron-job.py
> +        details = get_subject_version_details(subject, first_version)
details -> schema

2024-10-01 05:50 UTC, laxmanchekka commented on compatibility-changer/compatibility-changer/requirements.txt
> +tqdm==4.66.5
Comment from @ravisingal : Progress bar may not be required for cron.

2024-10-01 11:09 UTC, laxmanchekka submitted a review, later dismissed

2024-10-01 11:11 UTC, laxmanchekka commented
@ravisingal : can you please check this from helm, k8s and git actions perspective as well

2024-10-01 11:12 UTC, ravisingal commented on helm/templates/schema-compatibility/cronjob.yaml
> +            {{- toYaml .Values.schemaCompatibility.cronjob.securityContext | nindent 12 }}
```suggestion
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
```

2024-10-01 11:14 UTC, ravisingal commented on helm/templates/schema-compatibility/cronjob.yaml
> +          {{- end }}
```suggestion
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 14 }}
          {{- end }}
```

2024-10-01 11:14 UTC, ravisingal commented on helm/templates/schema-compatibility/cronjob.yaml
> +          {{- with .Values.schemaCompatibility.cronjob.podAnnotations }}
```suggestion
          {{- with merge .Values.schemaCompatibility.cronjob.podAnnotations .Values.commonPodLabels }}
```

2024-10-01 11:15 UTC, ravisingal commented on helm/templates/schema-compatibility/cronjob.yaml
> +          {{- with .Values.schemaCompatibility.cronjob.podLabels }}
```suggestion
          {{- with merge .Values.schemaCompatibility.cronjob.podLabels .Values.commonPodLabels }}
```

2024-10-01 11:16 UTC, ravisingal commented on helm/values.yaml
> +    securityContext: {}
```suggestion
```

2024-10-03 05:47 UTC, kishansairam9 commented on schema-compatibility/build.gradle.kts
> +  }
add `dockerFile.set(file("Dockerfile"))`

2024-10-03 05:48 UTC, kishansairam9 commented on schema-compatibility/build.gradle.kts
> +    imageName.set("schema-compatibility")
do we need this?

2024-10-03 07:18 UTC, laxmanchekka approved these changes

2024-10-03 07:28 UTC, merged